version: "3.5"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        container_name: craftech-front
        ports:
            - target: 80
              published: 8081
        networks:
            webapp-net:
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        container_name: craftech-back
        ports:
            - target: 8000
              published: 8080
        depends_on:
            - db
        networks:
            webapp-net:
        env_file:
            - ./backend/.env
    db:
        image: postgres:13.3-alpine
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            webapp-net:
networks:
    webapp-net:    